# Generated by Django 4.2.16 on 2024-10-06 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_materialstock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MaterialStock',
        ),
    ]
