# Generated by Django 4.2.16 on 2024-10-06 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_material_cantidad_real_material_supervisado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='cantidad_real',
        ),
    ]
