# Generated by Django 5.1.3 on 2024-11-20 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_materiales'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_total', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_pedida', models.PositiveIntegerField()),
                ('cliente_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PuntoRecoleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Recoleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_cargada', models.PositiveIntegerField()),
                ('cantidad_real', models.PositiveIntegerField()),
                ('es_validado', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Materiales',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='cantidad',
            new_name='cantidad_total',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='material',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='material',
            name='supervisado',
        ),
        migrations.RemoveField(
            model_name='material',
            name='user',
        ),
        migrations.AddField(
            model_name='deposito',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.material'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='deposito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.deposito'),
        ),
        migrations.AddField(
            model_name='recoleccion',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.material'),
        ),
        migrations.AddField(
            model_name='recoleccion',
            name='punto_recoleccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.puntorecoleccion'),
        ),
        migrations.AddField(
            model_name='recoleccion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
