# Generated by Django 5.1.3 on 2024-11-24 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_deposito_pedido_puntorecoleccion_recoleccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materiales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('cantidad_total', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='deposito',
        ),
        migrations.RemoveField(
            model_name='recoleccion',
            name='punto_recoleccion',
        ),
        migrations.RemoveField(
            model_name='recoleccion',
            name='material',
        ),
        migrations.RemoveField(
            model_name='recoleccion',
            name='user',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='cantidad_total',
            new_name='cantidad',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='nombre',
            new_name='material',
        ),
        migrations.AddField(
            model_name='material',
            name='supervisado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='material',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Deposito',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.DeleteModel(
            name='PuntoRecoleccion',
        ),
        migrations.DeleteModel(
            name='Recoleccion',
        ),
    ]
