# Generated by Django 5.1.3 on 2024-11-24 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_zona_material_cantidad_real_material_id_zona'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiales',
            name='costo_unitario',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
