# Generated by Django 4.2.16 on 2024-11-28 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_zona_material_cantidad_real_and_more'),
        ('usuarios', '0011_materiales_costo_unitario'),
    ]

    operations = [
    ]
